FROM java:8
VOLUME /tmp
ADD ./target/modelweb.jar /app.jar
RUN bash -c 'touch /app.jar'
EXPOSE 8131
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]